### PR TITLE
2058 enable logging to a variety of channels

### PR DESCRIPTION
**Pull request by hokiegeek2**
This is a draft PR corresponding to #2058. This draft PR only features integrating the OutputHandler and LogChannel classes into logging

### CODE REVIEW

**Review by Ethan-DeBandi99 — COMMENTED** [review]
Initial pass through, this looks good to me. I think you should be good to make all other supporting changes

**Review by jaketrookman — APPROVED** [review]
Looks good to me

**Review by joshmarshall1 — APPROVED** [review]

**Comment by hokiegeek2** [comment]
@Ethan-DeBandi99 @pierce314159 @joshmarshall1 @jaketrookman ready for final review

**Review by Ethan-DeBandi99 — APPROVED** [review]

**Comment by hokiegeek2** [comment]
see #2058 for screen shots of both OutputHandlers in action

**Review by joshmarshall1 — APPROVED** [review]

**Review by pierce314159 — APPROVED** [review]
Looks good to me! Having the option to write the logs to file is awesome!

**Pull request merged**
