### PR TITLE
Closes #1486 - Add Flake8 to CI

### LINKED ISSUE #1486: Add Flake8 to CI
Now that formatting of the fils is complete, we should add flake8 as a step to the CI.yml. This will allow for formatting to be automatically verified.

Part of #1395

### PR DESCRIPTION
**Pull request by Ethan-DeBandi99**
Closes #1486 

- Adds flake8 step to CI
  - flake8 will fail if any errors are found
 - Updated some files to resolve errors. Some are ignoring QA with `# noqa` tag.

### CODE REVIEW

**Comment by Ethan-DeBandi99** [comment]
Verified that flake8 failes when known errors are present. I will remove these a set for review.

This may result in merge conflicts with #1484.

**Review by pierce314159 — APPROVED** [review]
Awesome!!

**Comment by mhmerrill** [comment]
@Ethan-DeBandi99 does `flake8` belong in the lint processing? also can it print a success message like `mypy`? i.e. `"success: 33 files processed no issues found."` or something like that?

**Comment by pierce314159** [comment]
> does `flake8` belong in the lint processing? 

It certainly could go in the `lint` section since it is a linter. I personally think having it as it's own section makes it easier to tell what is breaking at a glance (python vs chapel), but that's just a matter of preference
> also can it print a success message like `mypy`? i.e. `"success: 33 files processed no issues found."` or something like that?

unfortunately, i don't think there's a way to do this. `flake8` doesn't print anything by default when there are no errors and adding `-v` leads to a lot of unnecessary info being printed

**Review by joshmarshall1 — APPROVED** [review]

**Pull request merged**
