### PR TITLE
Sparse matrix printing

### PR DESCRIPTION
**Pull request by ShreyasKhandekar**
Adds printing support for Sparse Matrices as follows:

```python
>>> a = ak.random_sparse_matrix(100, 0.05, "CSC")
>>> print(a)
  (4, 1)        0
  (8, 1)        0
  (22, 1)       0
  :     :
  (63, 100)     0
  (97, 100)     0
  (98, 100)     0

>>> a = ak.random_sparse_matrix(100, 0.05, "CSR")
>>> print(a)
  (1, 5)        0
  (1, 51)       0
  (1, 53)       0
  :     :
  (100, 29)     0
  (100, 52)     0
  (100, 95)     0
```

This matches how SciPy prints their sparse matrices.

Also added a new `nnz` member to the sparrayclass to easily query the number of non zeroes in the sparse matrix.

Due to the vertical format of printing here, I've kept the threshold to 20 NNZ instead of 100 which is the standard for pdarrays.

### CODE REVIEW

**Review by bmcdonald3 — APPROVED** [review]
Looks good, thanks Shreyas.

**Comment by ShreyasKhandekar** [comment]
Looks like the merge failed due to some sort of error getting the hdf5 package for testing. 

The error I see is as follows:

```console
Setting up libhdf5-dev (1.10.6+repack-4+deb11u1) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/pkgconfig/hdf5-serial.pc to provide /usr/lib/x86_64-linux-gnu/pkgconfig/hdf5.pc (hdf5.pc) in auto mode
Processing triggers for libc-bin (2.31-13+deb11u10) ...
Installing iconv
rm -rf /__w/arkouda/arkouda//dep/build/libiconv-1.17 /__w/arkouda/arkouda//dep/libiconv-install
mkdir -p /__w/arkouda/arkouda//dep /__w/arkouda/arkouda//dep/build
cd /__w/arkouda/arkouda//dep/build && curl -sL https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz | tar xz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [Makefile:169: install-iconv] Error 2
```

This looks unrelated to my PR and is probably some sort of sporadic network error. I would just try adding this to the merge queue again and hope it passes this time.

**Comment by ShreyasKhandekar** [comment]
It looks like there was an issue on the gnu side of things, a broken link for libiconv maybe? 
https://github.com/Bears-R-Us/arkouda/pull/3594#pullrequestreview-2207630909 might be referring to the same thing we're seeing in this PR, so if it is fixed then we can just try merging again.

**Review by stress-tess — APPROVED** [review]
Looks good! And yah like @ShreyasKhandekar mentioned ftp.gnu.org was down for a bit, see https://github.com/Bears-R-Us/arkouda/issues/3595

But it's up now so I'll readd this to the merge queue

**Pull request merged**
