### PR TITLE
Closes 3818 -- eliminates warning messages about tilde vs not

### LINKED ISSUE #3819: Update ~ (deprecated) to not in tests
The make test gives about a half dozen warnings that the use of ~ with bools is deprecated, and that it should be replaced with not.  These instances are in series_test.py, util_test.py, and numpy/dtypes_test.py.

### PR DESCRIPTION
**Pull request by drculhane**
Closes #3819 -- this is really minimal.  Changes maybe 7 lines in 3 files.

### CODE REVIEW

**Review by jaketrookman — COMMENTED** [review]
This looks good, but it looks like there are 2 more examples of `assert ~` in `tests/util_functions.py`.

**Comment by drculhane** [comment]
> This looks good, but it looks like there are 2 more examples of `assert ~` in `tests/util_functions.py`.

Ah, thanks.  Not sure how i missed those.  I'll change those, too.

**Comment by drculhane** [comment]
Since the change to array_api tests requires multi-dim to test, I'm running another make before I push those changes up, even though the changes themselves were only in the python.

**Review by jaketrookman — APPROVED** [review]

**Review by ajpotts — APPROVED** [review]
Thanks Andy!

**Pull request merged**
