### PR TITLE
#1101 Use `computeOnSegments` for casting strings to numeric

### PR DESCRIPTION
**Pull request by reuster986**
This is part of #1101 and should improve performance of casting string arrays to numeric values when the locality of the string bytes is poor.

Performance is tracked in one of the benchmarks added in #1106 , but I have not yet been able to run this at a significant scale to verify the expected improvement.

While here, also add more robust error handling to str-to-num casts. It now supports three modes:
- strict (default): raise an exception if any value cannot be converted
- ignore: never raise an exception, bad inputs result in a dtype-dependent default/nan value
- return_validity: same result as 'ignore', but also return a bool array showing where the conversion succeeded.

I am not wild about adding another `Enum` for the error handling mode, because it feels rather annoying as a user. Can anyone think of a better way?

### CODE REVIEW

**Comment by ronawho** [comment]
16-node-cs-hdr performance:

Before:
```
Casting good locality Average time = 22.1167 sec
Casting good locality Average rate = 0.0758 GiB/sec
Casting poor locality Average time = 45.3778 sec
Casting poor locality Average rate = 0.0369 GiB/sec
```


Now:
```
Casting good locality Average time = 0.0950 sec
Casting good locality Average rate = 17.6440 GiB/sec
Casting poor locality Average time = 0.2211 sec
Casting poor locality Average rate = 7.5834 GiB/sec
```

In table form:

| config        | Before     | Now        |
| ------------- | ---------: | ---------: |
| good locality | 0.07 GiB/s | 17.6 GiB/s |
| poor locality | 0.03 GiB/s |  7.5 GiB/s |

So great improvements for good and poor locality.

**Comment by reuster986** [comment]
Wow, cool! I will have to go back and rationalize that speedup to myself, because I didn't expect it, but will definitely take it :)

Thanks again for running the measurement!

**Comment by pierce314159** [comment]
The only idea I have to avoid the `Enum` would be to have a separate cast function to handle the `ignore` and `return_validity` cases. So `cast` would handle the strict case and `relaxed_cast(return_validity = False)` would handle the other two. It's hard to tell if this would be more or less annoying though

**Review by ronawho — APPROVED** [review]

**Review by bmcdonald3 — APPROVED** [review]

**Review by pierce314159 — APPROVED** [review]
Looks good to me!

**Pull request merged**
