### PR TITLE
test_histogram_multidim failing

### PR DESCRIPTION
**Pull request by stress-tess**
This has debug info for issue #3366, since I'm unable to reproduce this locally

Apparently it's failing on the nightly machine even in single locale mode. This make me think this a numeric precision issue somewhere with float math. It's really strange because the problem size lands us in the `+ reduce` case which has the simplest logic and very closely mirrors what is done in the 1d histogram case

we're seeing theses results for the first index of the 2d hist:
```
[11. 10. 12.  9. 10. 12.  7.  9. 11.  6.]
[10 10 11  9 10 11  7  9 11  6]
```
so we appear to undercounting by 1 inconsistently. I'm curious if these numbers are the same from run-to-run

### CODE REVIEW

**Comment by stress-tess** [comment]
here is what I see in the logs when I run this locally with a single locale:
```
xBins: 10
yBins: 10

xMin: 1
xMax: 99
yMin: 1
yMax: 99


xBinWidth: 9.8
yBinWidth: 9.8



Making sure we're in the small bound case

xiBin: 9
yiBin: 7
bucket_idx: 97

xiBin: 9
yiBin: 6
bucket_idx: 96

xiBin: 5
yiBin: 2
bucket_idx: 52

xiBin: 8
yiBin: 5
bucket_idx: 85

xiBin: 5
yiBin: 7
bucket_idx: 57

xiBin: 7
yiBin: 4
bucket_idx: 74

xiBin: 3
yiBin: 6
bucket_idx: 36

xiBin: 7
yiBin: 6
bucket_idx: 76

xiBin: 2
yiBin: 7
bucket_idx: 27


the zero bucket indices:
87, 93, 568, 571, 611, 616, 654, 784, 834, 924, 973,
```

**Comment by bmcdonald3** [comment]
Running this branch, the test is passing and I am seeing the same debug output. Recompiling from Arkouda's head to make sure I can still reproduce the failure

```
xBins: 10
yBins: 10

xMin: 1
xMax: 99
yMin: 1
yMax: 99


xBinWidth: 9.8
yBinWidth: 9.8



Making sure we're in the small bound case

xiBin: 9
yiBin: 7
bucket_idx: 97

xiBin: 9
yiBin: 6
bucket_idx: 96

xiBin: 5
yiBin: 2
bucket_idx: 52

xiBin: 8
yiBin: 5
bucket_idx: 85

xiBin: 5
yiBin: 7
bucket_idx: 57

xiBin: 7
yiBin: 4
bucket_idx: 74

xiBin: 3
yiBin: 6
bucket_idx: 36

xiBin: 7
yiBin: 6
bucket_idx: 76

xiBin: 2
yiBin: 7
bucket_idx: 27


the zero bucket indices:
87, 93, 568, 571, 611, 616, 654, 784, 834, 924, 973,
```

**Comment by bmcdonald3** [comment]
Interesting... From master, when I compile with `ARKOUDA_QUICK_COMPILE`, I am unabe to reproduce, but with optimizations enabled, I am able to reproduce...

I think we may have just uncovered a way to reproduce this locally!

**Comment by bmcdonald3** [comment]
Nevermind, could not reproduce this locally with a `COMM=none` build with optimizations enabled or a `COMM=gasnet` build, so back to square one with that idea...

**Comment by bmcdonald3** [comment]
So, I am seeing the same output on the server, but the client is still messed up...

**Comment by stress-tess** [comment]
I just pushed up an update re-enabling the `forall` loop. I'm seeing this from the client print statements
```python

np_hist[0]
[11. 10. 12.  9. 10. 12.  7.  9. 11.  6.]

ak_hist[0]
[11 10 12  9 10 12  7  9 11  6]
```

and this from the (important) server prints: (note this can be in any order but all 11 should be the same from run to run)
```
the zero bucket indices:

87

93

924

973

654

568

611

571

834

616

784
```

**Comment by bmcdonald3** [comment]
These are the minimal modules for this tst:
```
IndexingMsg
SequenceMsg
RandMsg
ReductionMsg
EfuncMsg
GenSymIO
HistogramMsg
OperatorMsg
```

And here is the command I'm using to run:
```
ARKOUDA_RUNNING_MODE=CLIENT python3 -m pytest PROTO_tests/tests/numeric_test.py -k test_histogram_multidi
```

**Comment by bmcdonald3** [comment]
Interesting, with the current state of the branch, I am unable to reproduce this with either 1 or 8 locales after the updates

Here is what I'm seeing from the server:
```
the zero bucket indices:

93

87

834

568

924

784

571

611

973

616

654
```

so appears the same as you have posted above.

**Comment by stress-tess** [comment]
welp removing the `writeln`s caused this to fail again. so this is beyond me. @brandon-neth was kind enough to offer to take this one off my hands :hearts:

**Comment by stress-tess** [comment]
I'll go ahead and close this PR since I'm not actively working it anymore but let me know if there's anything I can do to help!

**Pull request closed without merging**
