### PR TITLE
Resolves #3467: Fix indexing error in DataFrame instantiation

### LINKED ISSUE #3467: indexing error in DataFrame instantiation
**To Reproduce**
```
from arkouda import *

def perturb(a: ak.pdarray, atol: float, rtol: float, rng=None):
   if rng is None:
       rng = ak.random.default_rng()
   return a + rtol * a + atol * rng.random()

size = 100

rng = ak.random.default_rng()
atol = 0.001
rtol = 0.001
a = ak.arange(size, dtype="float64")
a2 = perturb(a, atol=atol, rtol=rtol, rng=rng)
idx2 = Index(a2)
df = DataFrame({"col1": a2}, index=idx2)
pd_df = df.to_pandas(retain_index=True)
ak_df = ak.DataFrame(pd_df)

```
Retuns a `KeyError: 0`.

### PR DESCRIPTION
**Pull request by ajpotts**
Closes #3467 indexing error in DataFrame instantiation

### CODE REVIEW

**Comment by stress-tess** [comment]
it seems like this PR is for #3426 not 426

**Comment by ajpotts** [comment]
If fixed the typo in the ticket number, and combined with ticket #3467, which is for a similar type of bug.

**Comment by stress-tess** [comment]
I don't think that the behavior reported in #3426 has changed, but it does look like #3467 has been fixed. The reproducer in #3426 is missing the `retain_index` flag that is in the PR description

both reproducers on master:
```python
In [3]: size=100
   ...: a = ak.arange(size, dtype="float64")
   ...: idx = ak.Index(a)
   ...: df = ak.DataFrame({"col1": a}, index=idx)
   ...: df_retain_idx = ak.DataFrame(df.to_pandas(retain_index=True))
   ...: df_dont_retain = ak.DataFrame(df.to_pandas())
   ...: print(df.index.inferred_type)
   ...: print(df_retain_idx.index.inferred_type)
   ...: print(df_dont_retain.index.inferred_type)
floating
floating
integer

In [4]: from arkouda import *
   ...:
   ...: def perturb(a: ak.pdarray, atol: float, rtol: float, rng=None):
   ...:    if rng is None:
   ...:        rng = ak.random.default_rng()
   ...:    return a + rtol * a + atol * rng.random()
   ...:
   ...: size = 100
   ...:
   ...: rng = ak.random.default_rng()
   ...: atol = 0.001
   ...: rtol = 0.001
   ...: a = ak.arange(size, dtype="float64")
   ...: a2 = perturb(a, atol=atol, rtol=rtol, rng=rng)
   ...: idx2 = Index(a2)
   ...: df = DataFrame({"col1": a2}, index=idx2)
   ...: pd_df = df.to_pandas(retain_index=True)
   ...: ak_df = ak.DataFrame(pd_df)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)

KeyError: 0
```

both reproducers with this PR:
```python
In [3]: size=100
   ...: a = ak.arange(size, dtype="float64")
   ...: idx = ak.Index(a)
   ...: df = ak.DataFrame({"col1": a}, index=idx)
   ...: df_retain_idx = ak.DataFrame(df.to_pandas(retain_index=True))
   ...: df_dont_retain = ak.DataFrame(df.to_pandas())
   ...: print(df.index.inferred_type)
   ...: print(df_retain_idx.index.inferred_type)
   ...: print(df_dont_retain.index.inferred_type)
floating
floating
integer

In [4]: from arkouda import *
   ...:
   ...: def perturb(a: ak.pdarray, atol: float, rtol: float, rng=None):
   ...:    if rng is None:
   ...:        rng = ak.random.default_rng()
   ...:    return a + rtol * a + atol * rng.random()
   ...:
   ...: size = 100
   ...:
   ...: rng = ak.random.default_rng()
   ...: atol = 0.001
   ...: rtol = 0.001
   ...: a = ak.arange(size, dtype="float64")
   ...: a2 = perturb(a, atol=atol, rtol=rtol, rng=rng)
   ...: idx2 = Index(a2)
   ...: df = DataFrame({"col1": a2}, index=idx2)
   ...: pd_df = df.to_pandas(retain_index=True)
   ...: ak_df = ak.DataFrame(pd_df)


```

**Comment by ajpotts** [comment]
I made the changes requested.

**Review by stress-tess — APPROVED** [review]

**Review by jaketrookman — APPROVED** [review]

**Pull request merged**
