### PR TITLE
Fix documentation for encode/decode

### PR DESCRIPTION
**Pull request by bmcdonald3**

### CODE REVIEW

**Comment by Ethan-DeBandi99** [comment]
@bmcdonald3 - can you correct the `mypy` and `flake8` issues? Thanks!

**Comment by bmcdonald3** [comment]
Shoot, sorry about that. Should be good to go now.

**Review by Ethan-DeBandi99 — APPROVED** [review]
Looks good to me.

**Review by pierce314159 — APPROVED** [review]
looks good!

**Pull request merged**
