### PR TITLE
834 file magic

### PR DESCRIPTION
**Pull request by glitch**
Issue #834

This PR adds the following:

- FileIO.chpl : File Magic detection using published Magic Header information for
    - HDF5
    - Parquet
    - Arrow
- Chapel unit test for magic detection and boundary conditions
- GenSymIO.chpl : Minor improvements and code reduction
    - Replacing `try!` with error handling in `arrayMsg` proc
    - Removing duplicate code in `processFilenames` the two procs were identical save for a `prepareGroup` proc which is now wrapped in conditional logic.

### CODE REVIEW

**Review by reuster986 — APPROVED** [review]
yay! progress towards I/O abstraction!

**Comment by reuster986** [comment]
@mhmerrill I haven't merged yet because doing so would close #834 and I wanted to give you a chance to weigh in before that point. We might want to start a new issue that tracks progress towards a full refactor.

**Comment by mhmerrill** [comment]
@glitch and @reuster986 Since we are doing incremental PRs to address issue #834 maybe we should have some sub issues that link to that issue which we can address and close with the subsequent PRs… what do you think?

**Comment by glitch** [comment]
> @glitch and @reuster986 Since we are doing incremental PRs to address issue #834 maybe we should have some sub issues that link to that issue which we can address and close with the subsequent PRs… what do you think?

I think that's a good idea.  I stopped refactoring at this point because it was about to get a lot more involved depending on the direction we want to go (see this [comment](https://github.com/Bears-R-Us/arkouda/issues/834#issuecomment-859683226))

**Pull request merged**
